spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bloggingdb
    username: postgres
    password: postgres
  main:
    banner-mode: off
server:
  port: 8080
file:
  upload-dir: uploads
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000